version: "2.1"

orbs:
  win: circleci/windows@5.0

workflows:
  build-and-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Print debug info
          command: dotnet --info
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --no-restore
      - run:
          name: Test
          command: dotnet test --no-build --logger:"trx"
      - run:
          name: Convert and move test results
          command: |
            dotnet tool install -g trx2junit
            & "%USERPROFILE%\.dotnet\tools\trx2junit" tests/**/TestResults/*.trx
            mkdir test-results
            Get-ChildItem -Recurse "tests/**/TestResults/*.xml" | ForEach-Object -Process { mkdir ([System.IO.Path]::Combine("test-results", $_.Directory.Parent.BaseName )); Move-Item -Path $_.FullName -Destination ([System.IO.Path]::Combine("test-results", $_.Directory.Parent.BaseName, $_.Name)) }
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
