name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Print Debug Info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Check formatting
      run: dotnet format --no-restore --verify-no-changes --severity error --exclude extern

    - name: Build
      run: dotnet build --no-restore

    - name: Setup code coverage
      run: dotnet tool install --global dotnet-coverage

    - name: Test and generate code coverage
      run: dotnet-coverage collect 'dotnet test --no-build --verbosity normal' -f xml -o 'coverage.xml'

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        fail_ci_if_error: false
        env_vars: OS
        flags: ${{ env.OS }}

    - name: Publish (Linux)
      if: runner.os == 'Linux'
      run: dotnet publish other/GameFinder.Example/GameFinder.Example.csproj -r linux-x64 -o ${{ github.workspace }}/bin/${{ runner.os }} --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true

    - name: Publish (Windows)
      if: runner.os == 'Windows'
      run: dotnet publish other/GameFinder.Example/GameFinder.Example.csproj -r win-x64 -o ${{ github.workspace }}/bin/${{ runner.os }} --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: GameFinder.Example-${{ runner.os }}-${{ github.sha }}
        path: ${{ github.workspace }}/bin/${{ runner.os }}/GameFinder*
        if-no-files-found: error
